package interfaces;

import logicadenegocios.*;
import utils.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author pollv
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
        public VentanaPrincipal() {
        initComponents();
        areaResultado2.setEditable(false);
        // Limpiar campoClave al hacer clic
        campoClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoClave.setText("");
            }
        });

        // Limpiar areaMensaje al hacer clic
        areaMensaje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaMensaje.setText("");
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        radioCifrar = new javax.swing.JRadioButton();
        radioDescifrar = new javax.swing.JRadioButton();
        comboAlgoritmo = new javax.swing.JComboBox<>();
        btnEjecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        areaResultado = new javax.swing.JScrollPane();
        areaResultado2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mensaje:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 55, -1));

        areaMensaje.setColumns(20);
        areaMensaje.setRows(5);
        jScrollPane1.setViewportView(areaMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 700, 150));

        jLabel2.setText("Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 37, 20));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 220, -1));

        buttonGroup1.add(radioCifrar);
        radioCifrar.setText("Cifrar");
        getContentPane().add(radioCifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 98, -1));

        buttonGroup1.add(radioDescifrar);
        radioDescifrar.setText("Descifrar");
        getContentPane().add(radioDescifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 98, -1));

        comboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cesar", "Llave", "Vigenere", "Palabra Inversa", "Mensaje Inverso", "Codigo Telefonico", "Binario", "RSA", "Triple DES", "AES" }));
        getContentPane().add(comboAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel3.setText("Resultado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        areaResultado2.setColumns(20);
        areaResultado2.setRows(5);
        areaResultado.setViewportView(areaResultado2);

        getContentPane().add(areaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 700, 160));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jButton1.setText("Enviar correo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed

    String mensaje = areaMensaje.getText().trim();
    String clave = campoClave.getText().trim();
    boolean cifrar = radioCifrar.isSelected();
    String algoritmo = comboAlgoritmo.getSelectedItem().toString();

    // Validar entrada
    if (!utils.Validador.esMensajeValido(mensaje, algoritmo)) {
        JOptionPane.showMessageDialog(this, "Mensaje invalido.");
        return;
    }


    if (!utils.Validador.esClaveValida(clave, algoritmo)) {
    JOptionPane.showMessageDialog(this, "Clave inválida.");
    return;
    }

    logicadenegocios.Mensaje msg;
    if (algoritmo.equals("Mensaje Inverso") || algoritmo.equals("Palabra Inversa")
        || algoritmo.equals("Codigo Telefonico") || algoritmo.equals("Binario")) {
        msg = new logicadenegocios.Mensaje(mensaje);  // Constructor sin clave
    } else {
        msg = new logicadenegocios.Mensaje(mensaje, clave);
    }



    // Seleccionar estrategia según el algoritmo
    logicadenegocios.GestorCifrado gestor = new logicadenegocios.GestorCifrado();
    switch (algoritmo) {
        case "Cesar":
            gestor.setEstrategia(new logicadenegocios.CifradorCesar());
            break;
        case "Llave":
            gestor.setEstrategia(new logicadenegocios.CifradorLlave());
            break;
        case "Vigenere":
            gestor.setEstrategia(new logicadenegocios.CifradorVigenere());
            break;
        case "Palabra Inversa":
            gestor.setEstrategia(new logicadenegocios.CifradorPalabraInversa());
            break;
        case "Mensaje Inverso":
            gestor.setEstrategia(new logicadenegocios.CifradorMensajeInverso());
            break;
        case "Codigo Telefonico":
            gestor.setEstrategia(new logicadenegocios.CifradorCodigoTelefonico());
            break;
        case "Binario":
            gestor.setEstrategia(new logicadenegocios.CifradorBinario());
            break;
        case "RSA":
            gestor.setEstrategia(new logicadenegocios.CifradorRSA());
            break;
        case "Triple DES":
            gestor.setEstrategia(new logicadenegocios.CifradorTripleDES());
            break;
        case "AES":
            gestor.setEstrategia(new logicadenegocios.CifradorAES());
            break;
        default:
            JOptionPane.showMessageDialog(this, "Algoritmo no reconocido.");
            return;
    }

    // Ejecutar la acción
    String resultado = cifrar ? gestor.cifrarMensaje(msg) : gestor.descifrarMensaje(msg);


    // Mostrar resultado
    areaResultado2.setText(resultado);

    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String correo = JOptionPane.showInputDialog(this, "Ingrese el correo al que desea enviar el resultado:");

        if (correo != null && !correo.trim().isEmpty()) {
            boolean existe = logicadenegocios.MailValidator.correoExiste(correo);
            System.out.println(logicadenegocios.MailValidator.validarCorreo(correo));
            
            if (existe) {
                JOptionPane.showMessageDialog(this, "Correo valido. Puedes enviar el resultado.");
                CuentaCorreo mensajero = new CuentaCorreo("no.reply.bancovital@gmail.com");
                mensajero.enviarCorreo(correo, "Mensaje en clave", areaResultado2.getText());
                
            } else {
                JOptionPane.showMessageDialog(this, "Correo invalido o no existe.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se ingresó ningún correo.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensaje;
    private javax.swing.JScrollPane areaResultado;
    private javax.swing.JTextArea areaResultado2;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoClave;
    private javax.swing.JComboBox<String> comboAlgoritmo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioCifrar;
    private javax.swing.JRadioButton radioDescifrar;
    // End of variables declaration//GEN-END:variables
}
