package interfaces;

import logicadenegocios.*;
import utils.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author pollv
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
        public VentanaPrincipal() {
        initComponents();
        areaResultado2.setEditable(false);
        // Limpiar campoClave al hacer clic
        campoClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoClave.setText("");
            }
        });

        // Limpiar areaMensaje al hacer clic
        areaMensaje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaMensaje.setText("");
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensaje = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        campoClave = new javax.swing.JTextField();
        radioCifrar = new javax.swing.JRadioButton();
        radioDescifrar = new javax.swing.JRadioButton();
        comboAlgoritmo = new javax.swing.JComboBox<>();
        btnEjecutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        areaResultado = new javax.swing.JScrollPane();
        areaResultado2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mensaje:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 55, -1));

        areaMensaje.setColumns(20);
        areaMensaje.setRows(5);
        jScrollPane1.setViewportView(areaMensaje);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 22, 220, 39));

        jLabel2.setText("Clave:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 67, 37, -1));
        getContentPane().add(campoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 89, 220, -1));

        buttonGroup1.add(radioCifrar);
        radioCifrar.setText("Cifrar");
        getContentPane().add(radioCifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 124, 98, -1));

        buttonGroup1.add(radioDescifrar);
        radioDescifrar.setText("Descifrar");
        getContentPane().add(radioDescifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 124, 98, -1));

        comboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cesar", "Llave", "Vigenere", "Palabra Inversa", "Mensaje Inverso", "Codigo Telefonico", "Binario", "Triple DES" }));
        getContentPane().add(comboAlgoritmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 123, -1, -1));

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel3.setText("Resultado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 208, -1, -1));

        areaResultado2.setColumns(20);
        areaResultado2.setRows(5);
        areaResultado.setViewportView(areaResultado2);

        getContentPane().add(areaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, -1, 40));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed

    String mensaje = areaMensaje.getText().trim().toLowerCase();
    String clave = campoClave.getText().trim().toLowerCase();
    boolean cifrar = radioCifrar.isSelected();
    String algoritmo = comboAlgoritmo.getSelectedItem().toString();

    // Validar entrada
    if (!utils.Validador.esMensajeValido(mensaje, algoritmo)) {
        JOptionPane.showMessageDialog(this, "Mensaje invalido.");
        return;
    }

    // Validar clave solo si el algoritmo la requiere
    if (!(algoritmo.equals("Mensaje Inverso") || 
      algoritmo.equals("Palabra Inversa") || 
      algoritmo.equals("Binario") || 
      algoritmo.equals("Codigo Telefonico"))) {

    if (!utils.Validador.esClaveValida(clave)) {
        JOptionPane.showMessageDialog(this, "Clave inválida.");
        return;
        }
    }


    // Crear objeto Mensaje
    // Crear objeto Mensaje
    logicadenegocios.Mensaje msg;
    if (algoritmo.equals("Mensaje Inverso") || algoritmo.equals("Palabra Inversa")
        || algoritmo.equals("Codigo Telefonico") || algoritmo.equals("Binario")) {
        msg = new logicadenegocios.Mensaje(mensaje);  // Constructor sin clave
    } else {
        msg = new logicadenegocios.Mensaje(mensaje, clave);
    }



    // Seleccionar estrategia según el algoritmo
    logicadenegocios.GestorCifrado gestor = new logicadenegocios.GestorCifrado();
    switch (algoritmo) {
        case "Cesar":
            gestor.setEstrategia(new logicadenegocios.CifradorCesar());
            break;
        case "Llave":
            gestor.setEstrategia(new logicadenegocios.CifradorLlave());
            break;
        case "Vigenere":
            gestor.setEstrategia(new logicadenegocios.CifradorVigenere());
            break;
        case "Palabra Inversa":
            gestor.setEstrategia(new logicadenegocios.CifradorPalabraInversa());
            break;
        case "Mensaje Inverso":
            gestor.setEstrategia(new logicadenegocios.CifradorMensajeInverso());
            break;
        case "Codigo Telefonico":
            gestor.setEstrategia(new logicadenegocios.CifradorCodigoTelefonico());
            break;
        case "Binario":
            gestor.setEstrategia(new logicadenegocios.CifradorBinario());
            break;
        case "Triple DES":
            gestor.setEstrategia(new logicadenegocios.CifradorTripleDES());
            break;
        case "AES":
            gestor.setEstrategia(new logicadenegocios.CifradorAES());
            break;
        default:
            JOptionPane.showMessageDialog(this, "Algoritmo no reconocido.");
            return;
    }

    // Ejecutar la acción
    String resultado = cifrar ? gestor.cifrarMensaje(msg) : gestor.descifrarMensaje(msg);


    // Mostrar resultado
    areaResultado2.setText(resultado);

    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensaje;
    private javax.swing.JScrollPane areaResultado;
    private javax.swing.JTextArea areaResultado2;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField campoClave;
    private javax.swing.JComboBox<String> comboAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioCifrar;
    private javax.swing.JRadioButton radioDescifrar;
    // End of variables declaration//GEN-END:variables
}
